In [1]:
import numpy as np

a = np.arange(10)
#(0,1,2,3,4,5,6,7,8,9)
print(a[3])
print(a[:])
print(a[:])
print(a[:-1])
#인덱스 2부터 2개씩
print(a[2::2])
#인덱스 7부터 2번 원소까지
print(a[7:2:-1])
# 마지막부터 처음까지 -1씩
print(a[::-1])

3
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[2 4 6 8]
[7 6 5 4 3]
[9 8 7 6 5 4 3 2 1 0]


In [5]:
a = np.arange(10)
print(a)
s = a[5:8]

print(s)
s[:] = 500 # 전체적으로 수정해라 -> (broadcasting)
print(s)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[500 500 500]
[  0   1   2   3   4 500 500 500   8   9]


In [10]:
a = np.arange(20).reshape((5,4))

print(a)


print(f"\n\na[2,3] =     {a[2,3]}")
print(f"a[0:5, 1 ] = {a[0:5, 1]}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


a[2,3] =     11
a[0:5, 1 ] = [ 1  5  9 13 17]


In [16]:
import numpy as np

a = np.random.rand(3, 4)
print("바뀌기전에 a의 값은 : ",a)
b = a
b[0, 1] = 10.0 #a도 바뀌게 된다 -> 얕은 복사
print(b)
print("바뀐 후 에 a의 값은 : ",a)

바뀌기전에 a의 값은 :  [[0.69548305 0.25111976 0.48105893 0.02708707]
 [0.72414619 0.25833851 0.57065912 0.26271828]
 [0.3267636  0.19891317 0.86642333 0.59215036]]
[[ 0.69548305 10.          0.48105893  0.02708707]
 [ 0.72414619  0.25833851  0.57065912  0.26271828]
 [ 0.3267636   0.19891317  0.86642333  0.59215036]]
바뀐 후 에 a의 값은 :  [[ 0.69548305 10.          0.48105893  0.02708707]
 [ 0.72414619  0.25833851  0.57065912  0.26271828]
 [ 0.3267636   0.19891317  0.86642333  0.59215036]]


In [17]:
import numpy as np

a = np.random.rand(3, 4)
print("바뀌기전에 a의 값은 : ",a)
b = a.copy()
b[0, 1] = 10.0 #a의 값은 변하지 않는다. -> 깊은 복사 
print(b)
print("바뀐 후 에 a의 값은 : ",a)

바뀌기전에 a의 값은 :  [[0.58575262 0.13492518 0.91883355 0.51543966]
 [0.65740558 0.55655821 0.93513971 0.99599251]
 [0.74030546 0.90163356 0.92120153 0.93024624]]
[[ 0.58575262 10.          0.91883355  0.51543966]
 [ 0.65740558  0.55655821  0.93513971  0.99599251]
 [ 0.74030546  0.90163356  0.92120153  0.93024624]]
바뀐 후 에 a의 값은 :  [[0.58575262 0.13492518 0.91883355 0.51543966]
 [0.65740558 0.55655821 0.93513971 0.99599251]
 [0.74030546 0.90163356 0.92120153 0.93024624]]


fancy indexing

In [11]:
import numpy as np

a = np.arange(20).reshape((5,4))
print(a, '\n')

b = a[(0, 2, 3), 2] # fancy indexing
print(b)

c = np.arange(20).reshape((5,4))
print(c, '\n')

rows = np.array([True, False, True, True, False])
d = a[rows, :] # boolean indexing
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[ 2 10 14]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
arr = np.array([1,2,3,4,5,6,7])
filter = arr % 2 != 0
newarr = arr[filter]

print(filter) # -> 핕러링 부합하는 요소들만 추출하게 하는 방법
print(newarr)

[ True False  True False  True False  True]
[1 3 5 7]


In [21]:
arr = np.array([1,2,3,4,5,4,4])
y = np.array([0,0,0,1,0,1,1])

x = arr[y==1]

print(x)

[4 4 4]


searching & filtering

In [23]:
#np.where(condition[, x, y])
#condition이 True이면 x를, False이면 y를 반환
#단, condition만 있는 경우에는 매칭된 요소의 **인덱스**들을 반환

import numpy as np

arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)

print(x)
print(x[0])
print(arr[x]) #filtering

(array([3, 5, 6]),)
[3 5 6]
[4 4 4]


In [26]:
import numpy as np

arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4, -1, arr)
print(x)


#where 사용 방법 -> 조건을 물을때*사용할때, 또는 참과 거짓에 반환에 사용할때
# 중요한 우선순이 fancy indexing, boolean inexing, filtering, 

[ 1  2  3 -1  5 -1 -1]


In [4]:
import numpy as np
a = np.arange(1, 2 ,0.2)
print(a)

[1.  1.2 1.4 1.6 1.8]


In [10]:
#최대, 최소값의 위치 구하기 (argmax, argmin)

import numpy as np

a = np.random.random_sample((3,4))
print(a)

print(f"argmax = {np.argmax(a)}")

print(f"argmax for axis 0 direction = {np.argmax(a, axis=0)}")                                                    

[[0.86460413 0.22631803 0.52832256 0.73690193]
 [0.09855523 0.53756502 0.07144762 0.13522083]
 [0.11820135 0.59279874 0.54349604 0.31138648]]
argmax = 0
argmax for axis 0 direction = [0 2 2 0]


In [14]:
#단위행렬 만들기
import numpy as np
import numpy.linalg as npl

a = np.eye(3)
print("a = \n", a, sep='')

b = np.array([[1,3], [2,4 ]])
print("b = \n", b, sep='')
# 역행렬 -> 
print("inverse matrix of b = \n", npl.inv(b), sep='')

a = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
b = 
[[1 3]
 [2 4]]
inverse matrix of b = 
[[-2.   1.5]
 [ 1.  -0.5]]


In [ ]:
#전치행렬 -> 행과 열을 바꾼거다
a = np.arange(24).reshape(2,4,3)

In [3]:
a = 0.1 
b = 0.2
print(a + b == 0.3)
print(0.1 + 0.2 == 0.3) 

False
False
